# Importing helper libraries

In [ ]:
!pip install --upgrade pip
!pip install "snowflake-connector-python[pandas]" "snowflake-snowpark-python[pandas]" snowflake-snowpark-python==1.9.0 numpy pandas matplotlib scikit-learn xgboost seaborn python-dateutil tqdm holidays faker
!pip install --upgrade --q snowflake-snowpark-python==1.9.0
!pip uninstall urllib3 -y
!pip install urllib3==1.26.15
!pip install fosforml==1.1.6

In [1]:
#from fosforio import snowflake
from fosforml import *
from fosforml.constants import MLModelFlavours
from matplotlib import pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', 500)
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np
import warnings; warnings.simplefilter('ignore')
from joblib import dump, load
import requests
from tqdm import tqdm
import time
import calendar

from time import sleep
import configparser
from dateutil.relativedelta import relativedelta
import datetime
from dateutil.easter import easter
from scipy.optimize import minimize_scalar
from scipy.optimize import curve_fit
import holidays, itertools

%matplotlib inline

# Reading the data

In [2]:
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [6]:
table_name = 'BOOKINGS_TRANSFORMED'
data = my_session.sql("select * from {}".format(table_name))
data = data.to_pandas()
data

,HOTEL,IS_CANCELED,LEAD_TIME,ARRIVAL_DATE_YEAR,MONTH,ARRIVAL_DATE_WEEK_NUMBER,ARRIVAL_DATE_DAY_OF_MONTH,EXPECTED_ARRIVAL_DATE,RESERVATION_STATUS,RESERVATION_STATUS_DATE,TOTAL_STAY_NIGHTS,TALLY_DAYS,STAYS_IN_WEEKEND_NIGHTS,STAYS_IN_WEEK_NIGHTS,ADULTS,CHILDREN,BABIES,TOTAL_GUESTS,AVG_ROOMS_PER_NIGHT,TOTAL_ROOM_NIGHTS,MEAL,COUNTRY,MARKET_SEGMENT,DISTRIBUTION_CHANNEL,PREVIOUS_CANCELLATIONS,PREVIOUS_BOOKINGS_NOT_CANCELED,RESERVED_ROOM_TYPE,ASSIGNED_ROOM_TYPE,DEPOSIT_TYPE,DAYS_IN_WAITING_LIST,CUSTOMER_TYPE,ADR,ARRIVAL_DATE_TRANSFORMED,RESERVATION_STATUS_DATE_TRANSFORMED
0,City Hotel,0,226,2023,8,35,29,2023-08-29,Check.Out,2023-01-15,4,4.000,2,2,2,0,0,2,1,4,BB,FRA,Offline TA/TO,TA/TO,0,0,A,A,No Deposit,0,Transient.Party,70.00,2023-08-29,2023-01-15
1,Resort Hotel,1,210,2024,3,9,3,2024-03-03,Canceled,2023-08-06,7,0.183,2,5,2,0,0,2,1,7,HB,PRT,Offline TA/TO,TA/TO,0,0,E,E,No Deposit,0,Transient,90.00,2024-03-03,2023-08-06
2,City Hotel,1,127,2023,9,37,12,2023-09-12,Canceled,2023-05-08,3,0.100,2,1,2,0,0,2,1,3,SC,BRA,Online TA,TA/TO,0,0,A,A,No Deposit,0,Transient,79.20,2023-09-12,2023-05-08
3,Resort Hotel,0,93,2023,8,34,27,2023-08-27,Check.Out,2023-05-26,6,6.000,2,4,2,0,0,2,1,6,HB,AUT,Online TA,TA/TO,0,0,E,E,No Deposit,0,Transient,102.93,2023-08-27,2023-05-26
4,Resort Hotel,0,18,2023,9,35,1,2023-09-01,Check.Out,2023-08-14,1,1.000,0,1,2,0,0,2,1,1,BB,ESP,Online TA,TA/TO,0,0,E,E,No Deposit,0,Transient.Party,80.00,2023-09-01,2023-08-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109613,City Hotel,0,81,2023,8,35,30,2023-08-30,Check.Out,2023-06-10,3,3.000,2,1,2,0,0,2,1,3,BB,IRL,Direct,Direct,0,0,A,A,No Deposit,0,Transient,79.80,2023-08-30,2023-06-10
109614,City Hotel,0,18,2023,8,35,30,2023-08-30,Check.Out,2023-08-12,3,3.000,2,1,2,0,0,2,1,3,SC,BEL,Online TA,GDS,0,0,E,E,No Deposit,0,Transient,145.00,2023-08-30,2023-08-12
109615,City Hotel,0,47,2023,8,35,31,2023-08-31,Check.Out,2023-07-15,2,2.000,1,1,2,0,0,2,1,2,BB,PRT,Direct,Direct,0,0,E,E,No Deposit,0,Transient,135.44,2023-08-31,2023-07-15
109616,City Hotel,1,72,2023,10,42,19,2023-10-19,Canceled,2023-08-08,4,0.470,1,3,2,0,0,2,1,4,SC,FRA,Online TA,TA/TO,0,0,A,A,No Deposit,0,Transient,74.80,2023-10-19,2023-08-08
109617,Resort Hotel,0,149,2023,8,34,26,2023-08-26,Check.Out,2023-03-30,7,7.000,2,5,2,0,0,2,1,7,BB,GBR,Online TA,TA/TO,0,0,A,A,No Deposit,0,Transient,49.94,2023-08-26,2023-03-30

In [7]:
data.columns = map(lambda x: str(x).lower(), data.columns)

In [9]:
def update_values(row):
    if row['hotel'] == 'City Hotel' and row['reserved_room_type'] == 'A':
        return 150
    elif row['hotel'] == 'City Hotel' and row['reserved_room_type'] == 'D':
        return 80
    elif row['hotel'] == 'City Hotel' and row['reserved_room_type'] == 'E':
        return 30
    elif row['hotel'] == 'Resort Hotel' and row['reserved_room_type'] == 'A':
        return 150
    elif row['hotel'] == 'Resort Hotel' and row['reserved_room_type'] == 'D':
        return 75
    elif row['hotel'] == 'Resort Hotel' and row['reserved_room_type'] == 'E':
        return 60
    else:
        pass

In [10]:
data['room_limit'] = data.apply(update_values, axis=1)

In [ ]:
hotels = data['hotel'].unique()

In [11]:
from scipy.optimize import curve_fit

# Define the demand curve function
def demand_curve(x, a, b, c, d, max_demand):
    demand = a * np.exp(-b * x) + c
    demand = np.where(x <= max_demand, np.minimum(demand, max_demand), demand)
    return demand + d

In [12]:
def revenue(price):
    return price * demand_curve(price, a_fit, b_fit,c_fit,d_fit,max_demand)

In [13]:
from scipy.optimize import brentq

def demand_to_price(num_rooms, a, b, c, d, max_demand):
    def root_func(x):
        return num_rooms - (a * np.exp(-b * x) + c)

    try:
        price = brentq(root_func, 0, 200)  # Adjust the interval bounds as needed
    except ValueError:
        # Fallback to default price if no root is found
        price_range=(0, 200)
        price = np.random.uniform(*price_range)

    return price

In [14]:
def generate_holiday_dates(start_year, end_year):
    holidays = {}
    for year in range(start_year, end_year + 1):
        holidays[datetime.date(year, 1, 1)] = 'new_year'
        easter_date = easter(year)
        holidays[easter_date] = 'easter'
        holidays[datetime.date(year, 12, 25)] = 'christmas'
    return holidays

holidays = generate_holiday_dates(2020, 2023)

In [15]:
def data_conversion(data):
    import holidays
    hotels = data['hotel'].unique()
    room_types = data['reserved_room_type'].unique()
    expanded_df = pd.DataFrame()
    for _, row in data.iterrows():
        num_stay_dates = row['total_rns']
        try:
            # Create a row for each stay date
            expanded_booking = pd.DataFrame({
                'hotel': row['hotel'],
                'room_type': row['reserved_room_type'], 
                'arrival_date': pd.date_range(start=row['expected_arrival_date'], periods=num_stay_dates),
                'total_rns': 1,
                'adr': row['adr'],
                'room_limit': row['room_limit']
            })

            # Append the stay date information to the new dataframe
            expanded_df = pd.concat([expanded_df, expanded_booking], ignore_index=True)
        except ValueError as e:
            print(f"Error processing booking for {row['hotel']} on {row['expected_arrival_date']} : {num_stay_dates} {e}")
    expanded_df = expanded_df.sort_values('arrival_date')
    expanded_df = expanded_df.reset_index(drop=True)
    expanded_df['adr']= np.round(expanded_df['adr'], 2)
           
    expanded_df['dow'] = expanded_df.arrival_date.dt.strftime('%A')
    expanded_df['month'] = expanded_df.arrival_date.dt.strftime('%B')

    return expanded_df

data['total_rns'] = data['stays_in_week_nights'] + data['stays_in_weekend_nights']

In [16]:
data = data[(data['is_canceled'] == 0) & (data['reservation_status'] !='No-Show')] 
data = data[(data.market_segment != 'Complementary') ]
data = data[(data.reserved_room_type == 'A') |(data.reserved_room_type == 'D') | (data.reserved_room_type == 'E')]

converted_df = data_conversion(data[['hotel', 'reserved_room_type', 'expected_arrival_date', 'adr', 'room_limit', 'total_rns']])
converted_df

,hotel,room_type,arrival_date,total_rns,adr,room_limit,dow,month
0,City Hotel,A,2022-05-01,1,80.00,150,Sunday,May
1,Resort Hotel,D,2022-05-01,1,153.00,75,Sunday,May
2,City Hotel,A,2022-05-01,1,101.50,150,Sunday,May
3,City Hotel,A,2022-05-01,1,80.00,150,Sunday,May
4,City Hotel,A,2022-05-01,1,101.50,150,Sunday,May
...,...,...,...,...,...,...,...,...
232598,Resort Hotel,E,2024-07-11,1,153.57,60,Thursday,July
232599,Resort Hotel,A,2024-07-12,1,99.06,150,Friday,July
232600,Resort Hotel,D,2024-07-12,1,112.80,75,Friday,July
232601,Resort Hotel,A,2024-07-13,1,99.06,150,Saturday,July
232602,Resort Hotel,D,2024-07-13,1,112.80,75,Saturday,July

In [17]:
converted_df["arrival_date"] = pd.to_datetime(converted_df["arrival_date"]).dt.strftime("%Y-%m-%d %H:%M:%S")

In [19]:
df_model=my_session.createDataFrame(
        converted_df.values.tolist(),
        schema=converted_df.columns.tolist())
df_model.write.mode("overwrite").save_as_table("TTH_DB.TTH_REV_OPT_Schema.CONVERTED_PRICING_DATA")

SnowparkSQLException: (1304): 01b6c248-070e-1713-0072-f303104931ba: 001795 (42601): SQL compilation error: error line 1 at position 132
maximum number of expressions in a list exceeded, expected at most 200,000, got 232,603

In [ ]:
session.sql("DROP PROCEDURE IF EXISTS CREATE_PRICING_MODEL(String)").collect()

In [ ]:
session.sql('''
CREATE OR REPLACE PROCEDURE create_pricing_model(table_name STRING)
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
PACKAGES = ('snowflake-snowpark-python', 'pandas', 'numpy', 'scipy')
HANDLER = 'create_pricing_model'
AS
$$
from snowflake.snowpark.session import Session
from snowflake.snowpark.functions import col
import pandas as pd
import numpy as np
from scipy.optimize import minimize_scalar, curve_fit, brentq
import itertools
def create_pricing_model(session, table_name=None):


    # Define functions
    def revenue(price):
        return price * demand_curve(price, a_fit, b_fit, c_fit, d_fit, max_demand)

    def demand_curve(x, a, b, c, d, max_demand):
        demand = a * np.exp(-b * x) + c
        demand = np.where(x <= max_demand, np.minimum(demand, max_demand), demand)
        return demand + d

    def demand_to_price(num_rooms, a, b, c, d, max_demand):
        def root_func(x):
            return num_rooms - (a * np.exp(-b * x) + c)

        try:
            price = brentq(root_func, 0, 200)
        except ValueError:
            price_range = (0, 200)
            price = np.random.uniform(*price_range)

        return price

    # Retrieve data from Snowflake table
    expanded_df = session.table([table_name]).to_pandas()
    expanded_df.columns = map(lambda x: str(x).lower(), expanded_df.columns)

    results = pd.DataFrame(columns=['month', 'hotel', 'room_limit', 'room_type', 'dow', 'optimal_rate', 'expected_rn', 'expected_rev', 'optimal_rate_lim_inv'])
    hotel_types = ['Resort Hotel', 'City Hotel']
    room_types = ['A', 'D', 'E']
    daily_rns = expanded_df.groupby(['arrival_date', 'dow', 'month', 'hotel', 'room_type']).agg({'room_limit': 'mean', 'total_rns': 'sum'}).reset_index()
    daily_rns = daily_rns.groupby(['dow', 'month', 'hotel', 'room_type']).agg({'room_limit': 'mean', 'total_rns': ['sum', 'mean', 'median']}).reset_index()
    daily_rns.columns = ['_'.join(col) for col in daily_rns.columns]
    adr_frequency = expanded_df.groupby(['dow', 'month', 'adr', 'hotel', 'room_type']).agg({'room_limit': 'mean', 'total_rns': 'sum'})
    adr_frequency.reset_index(inplace=True)
    merged_df = pd.merge(adr_frequency, daily_rns, how='left', left_on=['dow', 'month', 'hotel', 'room_type'], right_on=['dow_', 'month_', 'hotel_', 'room_type_'], suffixes=('_act', '_tot'))
    merged_df = merged_df.drop(['dow_', 'month_'], axis=1)
    merged_df['probability'] = merged_df['total_rns'] / merged_df['total_rns_sum']
    merged_df['expected_rns'] = merged_df['probability'] * merged_df['total_rns_median']
    merged_df = merged_df.sort_values(by=['dow', 'month', 'adr'], ascending=[True, True, False])
    merged_df['expected_demand'] = merged_df.groupby(['dow', 'month'])['expected_rns'].cumsum()
    merged_df['expected_rev'] = merged_df['adr'] * merged_df['expected_demand']
    results = pd.DataFrame(columns=['month', 'hotel', 'room_limit', 'room_type', 'dow', 'optimal_rate', 'expected_rn', 'expected_rev', 'optimal_rate_lim_inv'])
    months = merged_df.month.unique()
    dow = merged_df.dow.unique()

    for hotel in hotel_types:
        for room_type in room_types:
            for month in months:
                for day in dow:
                    data_subset = merged_df[(merged_df['dow'] == day) & (merged_df['hotel'] == hotel) & (merged_df['room_type'] == room_type) & (merged_df['month'] == month)].reset_index()
                    if data_subset.empty:
                        continue

                    mean = data_subset['adr'].mean()
                    std_dev = data_subset['adr'].std()
                    data_subset['z_scores'] = np.abs((data_subset['adr'] - mean) / std_dev)
                    data_subset = data_subset[data_subset['z_scores'] <= 2]

                    x_data = data_subset['adr'].values
                    y_data = data_subset['expected_demand'].values

                    try:
                        initial_guess = [1, 0.01, 1, 1, data_subset['total_rns_median'].values[0]]
                        bounds = ([0, 0, 0, 0, 0], [np.inf, np.inf, np.inf, np.inf, np.inf])
                        maxfev = 10000
                        params, _ = curve_fit(demand_curve, x_data, y_data, bounds=bounds, p0=initial_guess, maxfev=maxfev)
                    except RuntimeError as e:
                        print(f"Error fitting demand curve for {hotel}, {room_type}, {month}, {day}: {e}")
                        continue

                    a_fit, b_fit, c_fit, d_fit, max_demand = params

                    def revenue(price):
                        return price * demand_curve(price, a_fit, b_fit, c_fit, d_fit, max_demand)

                    objective = lambda price: -revenue(price)
                    optimize = minimize_scalar(objective, bounds=(45, 200), method='bounded')
                    optimal_price = optimize.x
                    max_revenue = -optimize.fun
                    expected_rns = demand_curve(optimal_price, a_fit, b_fit, c_fit, d_fit, max_demand)
                    optimal_rate_lim_inv = demand_to_price(data_subset['room_limit'].mean(), a_fit, b_fit, c_fit, d_fit, max_demand)

                    new_row = pd.DataFrame({'hotel': hotel, 'room_type': room_type, 'room_limit': data_subset['room_limit'].mean(), 'month': month, 'dow': day, 'optimal_rate': optimal_price, 'expected_rev': max_revenue, 'expected_rn': expected_rns, 'optimal_rate_lim_inv': optimal_rate_lim_inv}, index=[0])
                    results = pd.concat([results, new_row], ignore_index=True)

    results['optimal_rate'] = results['optimal_rate'].round()
    results['optimal_rate_lim_inv'] = results['optimal_rate_lim_inv'].round()
    results['expected_rn'] = results['expected_rn'].round().astype(int)
    results['expected_rev'] = results['expected_rev'].round()
    combinations = list(itertools.product(hotel_types, room_types))
    combinations_df = pd.DataFrame(combinations, columns=['hotel', 'room_type'])
    month_dict = {month: index for index, month in enumerate(pd.date_range('2020-01-01', periods=12, freq='M').strftime('%B'), 1)}

    new_data = pd.DataFrame()

    for year in range(2020, 2024):
        for month in month_dict.values():
            start_date = pd.to_datetime(f'{year}-{month}-01').replace(day=1)
            end_date = pd.to_datetime(f'{year}-{month}-01').replace(day=1) + pd.offsets.MonthEnd(0)
            date_range = pd.date_range(start_date, end_date, freq='D')
            df = pd.DataFrame(date_range, columns=['arrival_date'])
            df['dow'] = df['arrival_date'].dt.day_name()
            df['month'] = df['arrival_date'].dt.month_name()

            result_df = df.assign(key=1).merge(combinations_df.assign(key=1), on='key').drop('key', axis=1)
            new_data = pd.concat([new_data, result_df], ignore_index=True)

    final_data = pd.merge(new_data, results, how='left', on=['dow', 'hotel', 'room_type', 'month'])
    final_data.replace([np.inf, -np.inf], np.nan, inplace=True)
    final_data = final_data.dropna()
    final_data['room_limit'] = final_data['room_limit'].astype(int)
    final_data['arrival_date'] = pd.to_datetime(final_data['arrival_date']).dt.strftime("%Y-%m-%d %H:%M:%S")
    df_model = session.createDataFrame(final_data.values.tolist(), schema=final_data.columns.tolist())
    df_model.write.mode("overwrite").save_as_table("TTH_DB.TTH_REV_OPT_Schema.PROCESSED_PRICING_DATA")

    return "Data processed and dumped back to Snowflake"
$$
''').collect()

In [ ]:
converted_df.to_csv('./dates_dataset.csv', index=False)

In [ ]:
format_data(converted_df)

In [ ]:
register_model(None, 
               format_data, 
               name="predict_optimal_price", 
               description="predict_optimal_price",
               flavour=MLModelFlavours.sklearn,
               init_script="\\n pip install fosforml \\n pip install fosforio[snowflake] \\n pip install seaborn \\n pip install snowflake-connector-python[pandas] \\n pip install joblib==1.3.2 scikit-learn=1.3.2",
)